name: cmelab
channels:
  - conda-forge
  - mosdef
  - omnia
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - numpy
  - parmed
  - freud
  - fresnel
  - gsd
  - mbuild
  - hoomd
  - openbabel
  - py3Dmol
  - nodejs>=10
  - jupyterlab
  - pip:
    - "--editable=git+https://github.com/rsdefever/GAFF-foyer.git#egg=gaff_foyer-master"
    - git+https://github.com/mosdef-hub/foyer
